services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: lab_8
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/mysql

  web:
    build: .
    ports:
      - '8000:8000'
    volumes:
      - ./app:/app
    depends_on:
      - mysql
    restart: always
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=lab_8
      - API_KEY=d1558b3b04f23e7b02160135fd44853a
      - API_UNSPLASH=v4Tu1NKAVusR0CHlS0KL5XSmxXr4PcsjMbUQ1yDtDEY
